apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-config
  namespace: app-net
data:
  hostname: "fibonacci.com"
  ip: "172.18.0.2"
  as_ip: "10.9.10.2"
  as_port: "30001"

---

apiVersion: v1
kind: Service
metadata:
  name: fibonacci-dns
  namespace: app-net
spec:
  selector:
    app: fs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP
  clusterIP: 172.18.0.2

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fibonacci-ingress
  namespace: app-net
spec:
  rules:
    - host: fibonacci.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fibonacci-dns
                port:
                  number: 80
