
services:
  us:
    build:
      context: ./US  # Path to the directory containing the US code
    ports:
      - "8080:8080"
    networks:
      - app_net

  fs:
    build:
      context: ./FS  # Path to the directory containing the FS code
    ports:
      - "9090:9090"
    networks:
      - app_net
    depends_on:
      - as  # Ensure FS starts after AS

  as:
    build:
      context: ./AS  # Path to the directory containing the AS code
    ports:
      - "53533:53533"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
